export const BASE_PATH = "/";

export const routesURL = {
  LOGIN: `${BASE_PATH}login`,
  DASHBOARD: `${BASE_PATH}dashboard`,
  CUSTOMERDASHBOARD: `${BASE_PATH}home`,
  BACKLOG2: `${BASE_PATH}backlogg`,
  BACKLOG: `${BASE_PATH}backlog/`,
  BUDGET: `${BASE_PATH}budget`,
  FORECAST: `${BASE_PATH}forecast`,
  PORTFOLIO: `${BASE_PATH}portfolio`,
  PSR: `${BASE_PATH}psr/`,
  PROJECT_WIKI: `${BASE_PATH}projectwiki/`,
  DELIVERABLES_WIKI: `${BASE_PATH}deliverableswiki/`,
  DELIVERABLES_LIST: `${BASE_PATH}deliverableslist`,
  WORKPACKAGE_WIKI: `${BASE_PATH}workpackagewiki/`,
  WORKPACKAGE_LIST: `${BASE_PATH}workpackagelist`,
  TASK_WIKI: `${BASE_PATH}taskwiki`,
  MEETING: `${BASE_PATH}meeting/`,
  MEETING_LIST: `${BASE_PATH}meetinglist/`,
  ACTIVITIES_LIST: `${BASE_PATH}activitieslist`,
  RESOURCE_LIST: `${BASE_PATH}resourcelist/`,
  ISSUE_WIKI: `${BASE_PATH}issuewiki/`,
  ISSUE_LIST: `${BASE_PATH}issuelist/`,
  CHANGE_WIKI: `${BASE_PATH}changewiki/`,
  CHANGES_LIST: `${BASE_PATH}changeslist`,
  INVOICE_WIKI: `${BASE_PATH}invoicewiki`,
  INVOICE_LIST: `${BASE_PATH}invoicelist`,
  WBS: `${BASE_PATH}wbs`,
  RISK_WIKI: `${BASE_PATH}riskwiki`,
  RISK_LIST: `${BASE_PATH}risklist`,
  PAGE_NOT_FOUND: `${BASE_PATH}500`
};
